---
title: "Install LipidQuan"
author: "André Vidas Olsen"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


#Introduction
This vignette will describe how to install LipidQuan on a computer. In order to install LipidQuan, the user needs to have installed R first on the computer. For convenience, it is also recommended to install R studio. The following packages needs to be installed in R in order for LipidQuan to work:


ggplot2

reshape2

stats

utils

ComplexHeatmap

circlize

COMMENT: TIBERTI AND OTHERS: PLEASE CHECK TO SEE IF YOU ENCOUNTER REQUIREMENTS FOR OTHER PACKAGES TO BE INSTALLED AS WELL.



###Install LipidQuan from Bioconductor
COMMENT: (DOES NOT WORK AT THE MOMENT, SINCE THE PACKAGE IS NOT OUT AT BIOCONDUCTOR)

The easist way to install LipidQuan is to open R/RStudio and type the following two commands in the command line:

source("https://bioconductor.org/biocLite.R")

biocLite("lipidQuan")

###Install developmental version from GitHub
COMMENT: SINCE THIS THE GITHUB REPO IS AT THE MOMENT A PRIVATE REPO, THIS CAN NOT BE USED YET.



###Install LipidQuan from binary/source file
To install LipidQuan from source, open R/RStudio and type the following in the command line:

install.packages("path-to-file", repos = NULL, type="source")

, where "path-to-file" is the path to the source file. For example:

install.packages("../lipidQuan_0.1_R_x86_64-pc-linux-gnu.tar.gz", repos = NULL, type="source")


